name: CI-CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  #test:
  #  name: Test
  #  runs-on: ubuntu-latest
  #  needs: lint
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Install dependencies
  #      run: npm install
  #    - name: Test
  #      run: npm run test:ci

  #deploy:
  #  name: deploy
  # runs-on: ubuntu-latest
  #  needs: test
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Install dependencies
  #      run: npm install
  #    - name: build
  #      run: npm run build
